openapi: 3.0.0
info:
  title: Color Logic Test
  description: |
    Para 1: This is the first paragraph.
    
    Para 2: This paragraph should be removed and stay RED.
    
    Para 3: This one too.
    
    Creditor Payee
    Debtor Payer
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
