openapi: 3.0.0
info:
  title: Multiline Test
  description: |
    Para 1: This version of Payment Pre-validation API supports Beneficiary Account Verification service only. If the consumer wants to access other services like account format validation, purpose code validation, etc then they need to implement the v2.4.1 API Spec and call the v2 endpoint for those services.
    
    Para 2: This is a single API spec for the Consumers and the Data Providers.
    
    Para 3: Key changes are as below.
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
