openapi: 3.0.0
info:
  title: Test API
  description: The foreseen codes are documented externally by the verification service provider.
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
